### ISSUE TITLE
Explain the example

### ISSUE THREAD

**Issue by sgurukrupa** [rollup/rollup-plugin-svelte#1]
This is a question. In the example rollup.config.js for this plugin, what's the significance of using double asterisk ('src/components/**.html') in specifying the include property of the object being passed to svelte function? Wouldn't one asterisk be sufficient?

**Comment by Rich-Harris** [comment]
That's actually a typo – oops! It should be (and now is) `src/components/**/*.html`.

It's a [minimatch](https://github.com/isaacs/minimatch)-compatible glob pattern – the `**` token (pronounced 'globstar') means that it captures all `*.html` files beneath `src/components`, regardless of whether they're in nested directories.

Thanks for flagging it up.
