### ISSUE TITLE
Put pkg.svelte resolution logic in a separate module

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup-plugin-svelte#10]
So it can be used by e.g. svelte-loader

**Comment by Rich-Harris** [comment]
Come to think of it, it could live in Svelte itself, since any plugin is going to depend on it anyway

**Comment by Conduitry** [comment]
Closing. I don't think this is going to be worth the trouble, especially since only plugins and not loaders can control this in webpack, and support for this is built in with the `mainFields` option.
