### ISSUE TITLE
Does this plugin expose the compiler API?

### ISSUE THREAD

**Issue by arxpoetica** [rollup/rollup-plugin-svelte#20]
See for example: https://github.com/sveltejs/svelte/issues/820#issuecomment-345598850

**Comment by Rich-Harris** [comment]
Yep — any options passed to the plugin are also passed to the compiler, unless they have special meaning to the plugin (e.g. the plugin allows `css` to be a function for intercepting bundle-wide styles, which would make no sense for the compiler).
