### ISSUE TITLE
Svelte dependancy

### ISSUE THREAD

**Issue by Kiho** [rollup/rollup-plugin-svelte#25]
I have hard  time figuring out why my code referencing from local repo is not working.
```
"dependencies": {
....
    "svelte": "^1.46.0"
  }
```
Is this necessary to be there? or can this can be behind? last was 1.25.0 then jump to 1.46.0

**Comment by Rich-Harris** [comment]
I'm not sure I understand what problem you're experiencing?

One thing I've thought about doing is moving `svelte` to `peerDependencies`. That way you would have to install it separately, but you'd have total control over which version was used.

**Comment by Kiho** [comment]
My problem was this https://github.com/Kiho/svelte-redux-zero/blob/context-destroy/package.json#L28
was not working, this plugin is overriding that and installs 1.46.0.
I had to change `"rollup-plugin-svelte": "^3.1.0"` to `"rollup-plugin-svelte": "~3.1.0"`

**Comment by Rich-Harris** [comment]
I see. That would *probably* be fixed by using `peerDependencies`, I think

**Comment by Rich-Harris** [comment]
I've just released version 4 of this plugin — Svelte is now in `peerDependencies`, so hopefully this won't arise again.
