### ISSUE TITLE
Problems passing a glob to input param.

### ISSUE THREAD

**Issue by kokujin** [rollup/rollup-plugin-svelte#30]
I am trying to compile all the templates in the "template" folder

``````
export default {
    input: './templates/**/*.html',
    output: {
        file: 'assets/js/bundle.js',
        format: 'iife'
    },

``````

I am getting this error instead.

``````
[!] Error: Could not resolve entry (./templates/**/*.html)
``````
Can someone tell me what I am doing wrong? Thanks

**Comment by burningTyger** [comment]
Use https://github.com/kei-ito/rollup-plugin-glob-import to glob all html files. Despite the Readme you can also glob directories.

**Comment by Rich-Harris** [comment]
Closing as unrelated to this plugin
