### ISSUE TITLE
pkg.svelte not being respected when the pkg.main exists

### ISSUE THREAD

**Issue by kaisermann** [rollup/rollup-plugin-svelte#31]
My components have the following structure:

Package Name: `@repo/test`
```
dist/test.js     # Compiled component
src/index.js     # Imports and exports Test.svelte
src/Test.svelte  # Test component
...
```

If another component imports the `@repo/test` and the `dist` folder exists, `rollup-plugin-svelte` don't event read the `pkg.svelte`. That is making, for example, eslint complain about the compiled code 😭

**Comment by Conduitry** [comment]
This is a really old issue, but: Is this still happening? I'm not sure I understand what this is saying. `rollup-plugin-svelte` should be resolving to `pkg.svelte` if present. Is it not?

**Comment by kaisermann** [comment]
At the time, I was making a component library with both src and compiled components. When I linked them, to develop locally, if their `dist` directory existed, `rollup-plugin-svelte` would completely ignore the src files 🤔

However, I've abandoned that idea a long ago, since the components would hardly be used outside of a svelte context, and changed job, so I can't say if it's still happening 😬 

It could probably be some issue with linking packages + monorepo.

**Comment by Conduitry** [comment]
🤷‍♂
