### ISSUE TITLE
Pass `dependencies` from preprocessor response through in transform plugin

### ISSUE THREAD

**Issue by Conduitry** [rollup/rollup-plugin-svelte#40]
It would be nice for preprocessing to be able to make use of the feature available in Rollup 0.61+ that lets transforms specify additional files as dependencies, so that watching works properly.

This will be slightly fiddly as we'll have to intercept the responses from the `markup`/`style`/`script` callbacks to grab the `dependencies` from them, before passing the response along to `svelte.preprocess`. Then we'll compile the component (as we do now), and finally include those gathered dependencies in the response from the `transform` hook.

**Comment by Conduitry** [comment]
Opened PR #41. Still needs some readme updates to reflect the new feature.

**Comment by Rich-Harris** [comment]
closed via #41
