### ISSUE TITLE
Treeshake issue / generates dead code

### ISSUE THREAD

**Issue by dekdevy** [rollup/rollup-plugin-svelte#49]
```js
import DebugMenu from 'DebugMenu.html'

if(false){
   const debugMenu = new DebugMenu({})
}
```

The expected result would be an empty file due to Rollup removing the entire `if(false)..` block, and consequently also removing the import of the Debug module. But Rollup-plugin-svelte generates code regardless of the module being ever used. 
Even this would not be a problem because Rollup should be able to treeshake that generated code away as well. It cant however, because of one single line generated by the plugin, which causes Rollup to assume side-effects.

```js 
assign(DebugMenu.prototype, proto)
``` 

I tested this by manually removing the assign with another plugin in the plugin chain, and the resulting code is completely removed, as expected.  
Could this be avoided by having rollup-plugin-svelte check whether the module is actually used?

(Yes, this case should never exist and pre-compilers such as jscc would solve it, but I still wanted to ask about this)

**Comment by Conduitry** [comment]
With the new `/* @__PURE__ /*` function call annotations that were just added to Rollup yesterday, I think the best way to handle this would probably be to have the compiler itself add these in certain places. I don't think this is the sort of thing that the Svelte plugin wants to get involved in.

That said, I'm pretty sure this `assign()` to the prototype doesn't even exist in the output of Svelte v3 (which is just around the corner). Svelte v3 uses a regular `class ... extends ... {}`. If compiled components are already becoming completely treeshakable in v3, I don't think this warrants much (if any) time spent on it.

**Comment by dekdevy** [comment]
Sounds great, looking forward to Svelte v3. Thanks!
