### ISSUE TITLE
Render CSS To File?

### ISSUE THREAD

**Issue by Crisfole** [rollup/rollup-plugin-svelte#5]
I know there's a way to exclude the css from the javascript, does the rollup plugin include a way to spit that out into a file somewhere for those of us who prefer to load our styles all at once?

**Comment by Rich-Harris** [comment]
No but that would be an excellent addition. There isn't a great way for plugins to tell Rollup that they're generating additional files (there's an issue — https://github.com/rollup/rollup/issues/1084 — but we haven't made any progress on it yet) but it can sort of be done by abusing plugin hooks.

**Comment by Rich-Harris** [comment]
Sorry, I should have closed this issue a while back when this feature was added — this is now possible by passing a function as the `css` option:

```js
plugins: [
  svelte({
    css: styles => {
      fs.writeFileSync( 'public/main.css', styles );
    }
  })
]
```

It will call the function (with the concatenated styles for any imported components) every time the bundle is regenerated.

**Comment by Crisfole** [comment]
:+1: thanks! That's awesome.
