### ISSUE TITLE
Tree-shaking enabled?

### ISSUE THREAD

**Issue by frederikhors** [rollup/rollup-plugin-svelte#52]
Is tree-shaking (https://rollupjs.org/guide/en#tree-shaking) enabled with this plugin?

If I use `source-map-explorer` (https://github.com/danvk/source-map-explorer) with default Svelte 3 template (https://github.com/sveltejs/template) I see many `mjs` and `esm.js` files.

How to check if it's working?

**Comment by Conduitry** [comment]
Treeshaking isn't something that's configured or happens for individual plugins, it's something that happens to your bundle as a whole. It's configurable [here](https://rollupjs.org/guide/en#danger-zone) and defaults to enabled.

You can check whether it's working by looking at the bundle itself and seeing whether it contains any code from the files that it's not using. The sourcemap generally contains all of the code from all of the bundled files, regardless of whether the code is present in your final bundle.
