### ISSUE TITLE
Using scss files

### ISSUE THREAD

**Issue by frederikhors** [rollup/rollup-plugin-svelte#53]
If I wanna use `.scss` files what I need to do?

I can open a wiki page or a PR to explain this to newbies like me.

Thanks.

**Comment by frederikhors** [comment]
https://github.com/sveltejs/template/issues/34

**Comment by MaxMilton** [comment]
What you need is to use a style preprocessor. See the docs at <https://svelte.dev/docs#svelte_preprocess>.

If you don't want to write your own preprocessor there are some existing packages:

- https://github.com/kaisermann/svelte-preprocess
- https://github.com/ls-age/svelte-preprocess-sass

**Comment by frederikhors** [comment]
Ok, @MaxMilton I will write a PR for a wiki/FAQ page ASAP for newbies. Please do not close.
