### ISSUE TITLE
"Uncaught TypeError: node.removeEventListener is not a function" when use Svelte with jQuery on the same page 

### ISSUE THREAD

**Issue by constgen** [rollup/rollup-plugin-svelte#6]
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="../dist/main.js"></script>
```
When both Svelte and jQuery are included on the page there is an exception "Uncaught TypeError: node.removeEventListener is not a function"

The issue is caused by this function that is generated in the global namespace and rewrites a method of a `window` object
```js
function removeEventListener ( node, event, handler ) {
	node.removeEventListener ( event, handler, false );
}
```
Exception is thrown when jQuery calls this function
```js
/**
 * The ready event handler and self cleanup method
 */
function completed() {
	document.removeEventListener( "DOMContentLoaded", completed, false );
	window.removeEventListener( "load", completed, false );
	jQuery.ready();
}
```
In this case the compiled function is called but not native method and the first argument is "load" instead of DOM node.
The advised solution is to wrap all code generated by the compiler to a self invoked function and avoid rewriting of `window.removeEventListener()` method.

**Comment by Rich-Harris** [comment]
If `removeEventListener` is being declared in the global scope, it's because Rollup is generating an `es` module bundle — use `iife` instead to use the bundle as a `<script>` tag: https://github.com/rollup/rollup/wiki/JavaScript-API#format

```js
// rollup.config.js
import svelte from 'rollup-plugin-svelte';

export default {
  entry: 'src/main.js',
  dest: 'dist/main.js',
  format: 'iife',
  plugins: [ svelte() ]
};
```

**Comment by constgen** [comment]
You are absolutely right. Thanks.
Think this issue may be marked as resolved.
