### ISSUE TITLE
ssr mode not doing anything

### ISSUE THREAD

**Issue by fanckush** [rollup/rollup-plugin-svelte#64]
Does the ssr mode actually work? has anyone tried it?

**Comment by pngwn** [comment]
It actually works and I've tried it.

**Comment by Conduitry** [comment]
Compiling in SSR mode gives you javascript modules which your app is responsible for calling according to [their API](https://svelte.dev/docs#Server-side_component_API). It's then your app's responsibility to do whatever it wants with the returned strings. Compiling in SSR mode does not automatically generate any HTML files.
