### ISSUE TITLE
Uncaught ReferenceError: internal is not defined …

### ISSUE THREAD

**Issue by ha-douken** [rollup/rollup-plugin-svelte#80]
_rollup.config.js_
```
module.exports = {
  input: "comp.svelte",
  output: { file: "comp.js", format: "iife" },
  plugins: [ svelte() ]
}
```

_comp.svelte_
`<script> console.log("Hello World") </script>`

_output in browser console_
`Uncaught ReferenceError: internal is not defined at comp.js`

_comp.js_
```
(function (internal) {
  'use strict';

  /* comp.svelte generated by Svelte v3.12.1 */

  function create_fragment(ctx) {
  	return {
  		c: internal.noop,
  		m: internal.noop,
  		p: internal.noop,
  		i: internal.noop,
  		o: internal.noop,
  		d: internal.noop
  	};
  }

  function instance($$self) {
  	console.log("Hello World");

  	return {};
  }

  class Comp extends internal.SvelteComponent {
  	constructor(options) {
  		super();
  		internal.init(this, options, instance, create_fragment, internal.safe_not_equal, []);
  	}
  }

  return Comp;

}(internal));
```

**Comment by ha-douken** [comment]
Doing – what I think is the same – with svelte-cli works fine in the browser.
`npx svelte-cli compile --format iife comp.svelte > comp.js`

**Comment by Conduitry** [comment]
You need rollup-plugin-node-resolve. See #54. `svelte-cli` has been deprecated for a while, and would result in compiling as Svelte v2 components, not Svelte v3 components.

**Comment by ha-douken** [comment]
Thanks, but now I get an error `Comp is not defined` when I want to instantiate the component after loading it.

```
<!doctype html>
<script defer src=/comp.js></script>
<script type=module>
new Comp({ target: document.body })
</script>
```
